# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/bencode/all/bencode.rbi
#
# bencode-0.8.2
class Array
  def bencode; end
end
class Hash
  def bencode; end
end
class Integer < Numeric
  def bencode; end
end
class IO
  def bdecode; end
  def bencode; end
  def self.bdecode(filename); end
  def self.bencode(filename); end
end
class Object < BasicObject
  def bencode; end
end
class String
  def bdecode; end
  def bencode; end
end
module BEncode
  def self.dump(obj); end
  def self.load(str, opts = nil); end
  def self.load_file(path, opts = nil); end
end
class BEncode::Parser
  def eos?; end
  def initialize(stream); end
  def parse!; end
  def parse_dict!; end
  def parse_integer!; end
  def parse_list!; end
  def parse_string!; end
  def peek; end
  def stream; end
end
class BEncode::DecodeError < StandardError; end
class BEncode::EncodeError < StandardError; end
